"""Create goals table

Revision ID: d1f0cf8c5671
Revises: 4340b38b9d1e
Create Date: 2023-10-23 23:31:50.638406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f0cf8c5671'
down_revision = '4340b38b9d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accomplished', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.drop_column('accomplished')

    # ### end Alembic commands ###
